# Generated by Django 5.0.1 on 2026-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, max_length=1000, verbose_name='Link')),
                ('data_extracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Extração')),
                ('fonte', models.CharField(default='G1', max_length=200, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_extracao'],
            },
        ),
    ]
